// <auto-generated />
using HotelListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220820141701_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "UK",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "FR",
                            Name = "France"
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street",
                            CountryId = 5,
                            Name = "Hotel One",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Main Street",
                            CountryId = 4,
                            Name = "Hotel Two",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Main Street",
                            CountryId = 3,
                            Name = "Hotel Three",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 4,
                            Address = "1011 Main Street",
                            CountryId = 2,
                            Name = "Hotel Four",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "1213 Main Street",
                            CountryId = 1,
                            Name = "Hotel Five",
                            Rating = 5.5
                        });
                });

            modelBuilder.Entity("HotelListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
